baseURL = 'https://code-jones.github.io/tpc/'
languageCode = 'en-us'
title = 'Terrace Point Consulting Group'
DefaultContentLanguage = 'en'
enableInlineShortcodes = true
enableRobotsTXT = true

#googleAnalytics = "UA-12345678-1"


[params]

  showBlog = false
  mainSections = ['services']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "Terrace Point Consulting Group Logo"
    size = "h-10"

  [params.site]
    name = "Terrace Point Consulting Group"

  [params.icon]
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Terrace Point Consulting Group"
    meta_og_title = "Terrace Point Consulting Group"
    meta_og_type = "website"
    meta_og_url = "https://Terrace Point Consulting Group.pages.dev"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Terrace Point Consulting Group"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 1

  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/opera7133/tella"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2